### ISSUE TITLE
Object conversion: Java to JSON?

### ISSUE THREAD

**Issue by moonlitSpider** [StevenLooman/blammo#5]
Hello,

I happened upon blammo while trying to solve this problem: I am consuming messages from a RabbitMQ exchange, but those messages, written by a Java application, are objects of class ch.qos.**logback**.classic.spi.LoggingEvent.

I suspect that I need to deserialize these objects into a JSON object. Could blammo help with something like this? If not, are you aware of any node.js module that could?

Thanks for your guidance on this.

Cordially,

Paul

**Comment by StevenLooman** [comment]
Hi,

Thank for your question. Although a strange place to ask here... Blammo is a JavaScript library, not a Java library. Blammo cannot help you with this.

Nevertheless, at [json.org](http://json.org/) several Java libraries are listen which can be used to convert Java objects to JSON. Perhaps any of those can be of help to you.

Hope this helps,

Steven
